json.first_name employee.first_name
json.last_name employee.last_name
json.email employee.email
json.phone employee.phone
json.title employee.title
json.department_id employee.department_id
json.created_at employee.created_at
json.updated_at employee.updated_at
json.id employee.id
json.department employee.department